# Generated by Django 3.1.4 on 2020-12-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('amount', models.IntegerField()),
                ('expire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('percentage', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('cart_limitation', models.IntegerField()),
                ('expire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('percentage', models.IntegerField(default=0)),
                ('expire_date', models.DateField()),
                ('slug', models.CharField(max_length=256)),
            ],
        ),
    ]
