# Generated by Django 3.1.4 on 2020-12-20 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('user', '0001_initial'),
        ('sale', '0001_initial'),
        ('products', '0002_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.AddField(
            model_name='discount',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='product_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.productfamily'),
        ),
    ]
