# Generated by Django 3.1.4 on 2020-12-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20201220_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='status',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='status',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
