# Generated by Django 3.1.4 on 2020-12-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('category', '0002_auto_20201227_1344'),
        ('sale', '0003_auto_20201221_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='product_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='category.productfamily'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='cart_limitation',
            field=models.IntegerField(verbose_name='حداقل مبلغ سبد خرید'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=256, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expire_date',
            field=models.DateField(verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='maximum',
            field=models.IntegerField(verbose_name='ماکسیموم'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.IntegerField(verbose_name='درصد'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='status',
            field=models.CharField(max_length=128, null=True, verbose_name='وضضعیت'),
        ),
    ]
