# Generated by Django 3.1.4 on 2020-12-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20201227_1344'),
        ('user', '0001_initial'),
        ('sale', '0004_auto_20201227_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='cart_limitation',
            field=models.IntegerField(default=0, verbose_name='حداقل مبلغ سبد خرید'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.IntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(max_length=256, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='expire_date',
            field=models.DateField(verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='product_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='category.productfamily', verbose_name='دسته محصولات'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='status',
            field=models.CharField(max_length=128, null=True, verbose_name='وضعیت'),
        ),
    ]
