# Generated by Django 3.1.4 on 2020-12-20 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('sale', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='bonus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.bonus'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.discount'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productinstance'),
        ),
    ]
