# Generated by Django 3.1.4 on 2020-12-20 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('main_features', models.TextField(null=True)),
                ('brand', models.CharField(max_length=128, null=True)),
                ('images', models.TextField(null=True)),
                ('sale_count', models.IntegerField(default=0, null=True)),
                ('total_count', models.IntegerField(default=0, null=True)),
                ('available', models.IntegerField(default=0, null=True)),
                ('satisfaction', models.FloatField(default=0, null=True)),
                ('vote_counts', models.IntegerField(default=0, null=True)),
                ('comment_count', models.IntegerField(default=0, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category')),
                ('specifications', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filter.specificationlist')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.TextField(null=True)),
                ('count', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
