# Generated by Django 3.1.4 on 2020-12-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
        ('category', '0002_auto_20201227_1344'),
        ('user', '0001_initial'),
        ('products', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.IntegerField(default=0, null=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=128, null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment_count',
            field=models.IntegerField(default=0, null=True, verbose_name='تعداد نظرات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.TextField(null=True, verbose_name='تصاویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_features',
            field=models.TextField(null=True, verbose_name='ویژگی های اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_count',
            field=models.IntegerField(default=0, null=True, verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='satisfaction',
            field=models.FloatField(default=0, null=True, verbose_name='میزان رضایت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filter.specificationlist', verbose_name='لیست مشخصات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(max_length=255, null=True, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_count',
            field=models.IntegerField(default=0, null=True, verbose_name='تعداد کل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vote_counts',
            field=models.IntegerField(default=0, null=True, verbose_name='تعداد آرا'),
        ),
    ]
